on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts/*
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: yarn install and coverage
        run: |
          yarn install
          yarn build
          yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
